server:
  port: ${PORT:0}


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cambio-service

  datasource:
    url: "jdbc:mysql://localhost:13307/cambio-service-db?useTimezone=true&serverTimezone=UTC"
    username: "root"
    password: "root12345"

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


  flyway:
    url: "jdbc:mysql://localhost:13307/"
    schemas: "cambio-service-db"
    user: root
    password: "root12345"





springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs


