server:
  port: 8004

spring:
  application:
    name: cambio-service

  datasource:
    url: "jdbc:mysql://localhost:13307/cambio-service-db?useTimezone=true&serverTimezone=UTC"
    username: "root"
    password: "root12345"

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


  flyway:
    url: "jdbc:mysql://localhost:13307/"
    schemas: "cambio-service-db"
    user: root
    password: "root12345"


