server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cambio-service:
  url: 'http://localhost:8004/cambio-service/convert'
  default-from-value: 'USD'

spring:
  application:
    name: book-service


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:13308/book-service-db"
    username: "root"
    password: "root12345"



  flyway:
    url: "jdbc:mysql://localhost:13308/"
    schemas:
      - book-service-db
    user: "root"
    password: "root12345"



