spring:
  application:
    name:  greeting-service


management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

server:
  port: 18080


greeting-service:
  greeting: "Olá"
  default-value: "Mundo"
