server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

spring:
  application:
    name: mini-api-gateway
  cloud:
    gateway:
      routes:
        - id: cambio-service
          uri: lb://cambio-service
          predicates:
            - Path=/cambio-service/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**


